name = "mame-log"
compatibility_date = "2025-01-05"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "MAME_LOG_IMAGES"
id = "dc0b8fac145640ebb5ecbd32dab0087a"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "mame-log"
database_id = "e53e7a23-7c7f-4a89-8cd4-cc417b3fa792"

# [ai]
# binding = "AI"